---
format: html-eval-false
---

# Data transformations

Projection Pursuit Multivariate Transform was applied to the sample data.

Projection Pursuit Multivariate Transform (PPMT) is a method to transform multivariate numeric data into a multigaussian. The transform aims to remove all bivariate correlations between the variables making them independent and to transform each variable to a normal distribution. The transform allows for independent random simulation of gaussian variables which are then back-transformed into the original multivariate space where all bivariate correlations and trends are restored. The transform is useful in conditional simulations and kriging where the variables are assumed to be independent and gaussian. The transform ensures that, even when using different variograms for each variable, the bivariate relationships are maintained and any desired ratios are replicated.

```{r}
C__AH <- cache_data("./data/C/C__jura_samples_ppmt.rds", function() {
  x <- B__AH
  x$rowid <- 1:nrow(x)
  fldsy <- flds_est
  fldsx <- setdiff(names(x), fldsy)
  indx <- complete.cases(x[, fldsy])
  x <- x[indx, ]

  flds <- top_cuts$Variable
  cutval <- top_cuts$Cut
  names(cutval) <- flds
  for (i in flds) {
    x[[i]] <- ifelse(x[[i]] > cutval[[i]], cutval[[i]], x[[i]])
  }

  set.seed(3)
  y_ppmt <- ppmt(x[, fldsy])
  y_ppmt$Y <- cbind(x[, fldsx], y_ppmt$Y)

  return(y_ppmt)
})
```
